brew "powerlevel10k"
brew "bat"
brew "btop"
brew "fd"
brew "fnm"
brew "fzf"
brew "git"
brew "git-delta"
brew "glab"
# brew "go"
brew "gum"
brew "jq"
brew "lazygit"
# brew "mole"
# brew "phpantom-lsp"
brew "ripgrep"
brew "sesh"
brew "stow"
brew "tmux"
# brew "unar"
brew "zoxide"
brew "zsh"
# cask "antigravity-cli"
# cask "dbeaver-community"
cask "font-iosevka"
# cask "font-iosevka-aile"
cask "ghostty"
cask "google-chrome"
cask "karabiner-elements"
# cask "orbstack"
cask "raycast"
# cask "tableplus"
cask "visual-studio-code"
cask "zen"
